/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type Category = { 'Accessories' : null } |
  { 'Toys' : null } |
  { 'Belts' : null } |
  { 'PetFood' : null } |
  { 'Clothing' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'averageRating' : number,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface ProductFilter {
  'sortOrder' : [] | [SortOrder],
  'maxPrice' : [] | [bigint],
  'category' : [] | [Category],
  'keyword' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ProductId = bigint;
export interface Review {
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
  'reviewer' : UserId,
}
export type SortOrder = { 'PriceDesc' : null } |
  { 'PriceAsc' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addReview' : ActorMethod<[ProductId, bigint, string], boolean>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];