/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Category = IDL.Variant({
  'Accessories' : IDL.Null,
  'Toys' : IDL.Null,
  'Belts' : IDL.Null,
  'PetFood' : IDL.Null,
  'Clothing' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'averageRating' : IDL.Float64,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Review = IDL.Record({
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : UserId,
});
export const SortOrder = IDL.Variant({
  'PriceDesc' : IDL.Null,
  'PriceAsc' : IDL.Null,
});
export const ProductFilter = IDL.Record({
  'sortOrder' : IDL.Opt(SortOrder),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(Category),
  'keyword' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'Accessories' : IDL.Null,
    'Toys' : IDL.Null,
    'Belts' : IDL.Null,
    'PetFood' : IDL.Null,
    'Clothing' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'averageRating' : IDL.Float64,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Review = IDL.Record({
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : UserId,
  });
  const SortOrder = IDL.Variant({
    'PriceDesc' : IDL.Null,
    'PriceAsc' : IDL.Null,
  });
  const ProductFilter = IDL.Record({
    'sortOrder' : IDL.Opt(SortOrder),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(Category),
    'keyword' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };